wandb_version: 1

d_learning_rate:
  desc: null
  value: 8.676200826173473e-05
g_learning_rate:
  desc: null
  value: 8.649695225354906e-05
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696331178.403718
    t:
      1:
      - 1
      - 41
      - 55
      3:
      - 16
      - 23
      4: 3.10.9
      5: 0.15.8
      8:
      - 5
