wandb_version: 1

d_learning_rate:
  desc: null
  value: 0.000886251934378465
g_learning_rate:
  desc: null
  value: 0.0008264070253589756
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696335479.237938
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 2
      - 16
      - 17
      - 23
      - 37
      4: 3.10.9
      5: 0.15.8
      8:
      - 5
