wandb_version: 1

d_learning_rate:
  desc: null
  value: 0.000160538854387665
g_learning_rate:
  desc: null
  value: 0.0005557789786059115
_wandb:
  desc: null
  value:
    python_version: 3.10.9
    cli_version: 0.15.8
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696333926.51233
    t:
      1:
      - 1
      - 41
      - 55
      2:
      - 1
      - 41
      - 55
      3:
      - 1
      - 16
      - 17
      - 23
      - 37
      4: 3.10.9
      5: 0.15.8
      8:
      - 5
